kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30007  
      hostPort: 30008       
      protocol: TCP
- role: worker
  extraPortMappings:
    - containerPort: 30007  
      hostPort: 30010       
      protocol: TCP
